Collapse logging of run args by default
buildkite-plugins/docker-compose-buildkite-plugin pull request #407
Opened 2023-10-12 02:31 UTC by francoiscampbell

By default this plugin collects the run output in a `+++` group, while the `docker` plugin collects it in a `---` group. This PR unifies the two plugins by switching to using `---` by default (https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/36b85cc317745f868f2f6918a02f9cfb6a0b3069/commands/run.sh#L503).

The rationale for using `---` by default is that when we're passing lots of environment variables, volumes, etc, the `docker-compose run ...` command gets pretty long and having the log group expanded by default is noisy. Additionally, it's quite likely that the command being run will create a `+++` group of its own, so it's not necessary for the plugin to provide one by default.

For backwards compatibility, the `collapse-run-log-group` option has been added, which will restore the old behaviour.

2023-10-12 18:48 UTC, pzeballos commented on README.md
> +Default `true`
For backwards compatibility this should be `false` by default

2023-10-12 18:55 UTC, pzeballos requested changes
Thanks @francoiscampbell! I think this is reasonable, but you are changing the default behavior, if the default kept the current functionality will be ok to merge (and update the test 🙂 )

2023-10-16 18:56 UTC, francoiscampbell commented
Ok @pzeballos, I've flipped the default. Are we OK with the default being inconsistent between this plugin and the Docker one?

2023-10-19 21:06 UTC, pzeballos commented
> Ok @pzeballos, I've flipped the default. Are we OK with the default being inconsistent between this plugin and the Docker one?

yep, all good, they are different plugins, and we prefer not to do a backwards compatibility change at the moment :) 

The build is failing in the linter step @francoiscampbell , can you update the Readme to use v4.15.0? Thanks!

2023-10-23 14:27 UTC, francoiscampbell commented
Updated

2023-10-23 18:31 UTC, pzeballos approved these changes
Thanks!

2023-10-23 18:37 UTC, merged